name: CI

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'script.sh'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean working directory
        run: |
          git clean -fd
          git reset --hard

      - name: Checkout additional repositories
        run: |
          git clone https://github.com/DeSireFire/animeTrackerList.git .cache/animeTrackerList
          git clone https://github.com/XIU2/TrackersListCollection.git .cache/TrackersListCollection
          git clone https://github.com/ngosang/trackerslist.git .cache/trackerslist
          git clone https://github.com/hezhijie0327/Trackerslist.git .cache/Trackerslist
          git clone https://github.com/Azathothas/Trackers.git .cache/Trackers

      - name: Update .gitignore
        run: |
          echo ".cache/" >> .gitignore
          git add .gitignore
          git commit -m "Update .gitignore to exclude .cache directory" || echo "No changes to .gitignore"

      - name: Build
        run: bash script.sh

      - name: Config Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes
        run: |
          git add all.txt https.txt
          git commit -m "update: $(date) total: $(wc -l < all.txt), https: $(wc -l < https.txt)" || echo "No changes to commit"

      - name: Display file contents
        run: |
          echo "Total trackers in all.txt: $(wc -l < all.txt)"
          echo "Total trackers in https.txt: $(wc -l < https.txt)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
